# -*- coding: utf-8 -*-
"""IOTDataPreProcessing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9gQnC5794F-oTzoWlQzHp2xqTgCSByA
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# read in the dataset from your Drive
df = pd.read_csv('/content/drive/My Drive/SLIIT/Y4S1/ColomboRH.csv')

print(df)

#Filling missing data using mean of obs_val itself
df['obs_val'].fillna(df['obs_val'].mean(), inplace=True)

df.drop('year', axis=1, inplace=True)

df.drop('month', axis=1, inplace=True)

df.drop('day', axis=1, inplace=True)

df.head()

from google.colab import files

# Write the DataFrame to an Excel file
df.to_csv('my_data.csv', index=False)

# Download the Excel file from Colab
files.download('my_data.csv')